### check cluster

GET {{url}}/_cat/health


### best buy data

GET {{url}}/_cat/indices

###

#DELETE {{url}}/bbuy_products

###

GET {{url}}/bbuy_products/_count

###

GET {{url}}/bbuy_queries/_count

###

GET {{url}}/bbuy_products/_mapping

### Relevance and Ranking


GET {{url}}/bbuy_queries/_search
Content-Type: application/json

{
  "size": 0pho,
  "aggs": {
    "Query": {
      "terms": {
        "size": 10,
        "field": "query.keyword"
      },
      "aggs":{
        "Docs":{
          "terms":{
            "size": 5,
            "field": "sku.keyword"
          }
        }
      }
    }
  }
}


###

GET {{url}}//bbuy_queries/_search?q=query.keyword:"2622037 2127204 2127213 2121716 2138291"
Content-Type: application/json

###

GET {{url}}//bbuy_queries/_search?q=sku:2622037
Content-Type: application/json

###

GET {{url}}/bbuy_products/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "name": "i phone"
        }
    },
    "_source": "name"
}

###

GET {{url}}/bbuy_products/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "name.hyphens": "i-phone"
        }
    },
    "_source": "name"
}

###

GET {{url}}/bbuy_products/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "name":{
                "query": "iphone4",
                "fuzziness": 2
            }
        }
    },
    "_source": "name"
}
